document.write("Lay ngay hien tai : ");
var today = new Date();
document.write(today.getDate());
document.write("<br>");
document.write("Lay nam hien tai : ");
document.write(today.getFullYear());
document.write("<br>");
document.write("Lay gio hien tai : ");
document.write(today.getHours());
document.write("<br>");
document.write("Lay thang hien tai : ");
document.write(today.getMonth()+1);
document.write("<br>");
var birtday = new Date("1994-01-09");
document.write("Lay ngay sinh cua ban : ");
document.write(birtday.getDate());
document.write("<br>");
document.write("tuoi cua ban la : ");
document.write(today.getFullYear() - birtday.getFullYear());